server:
  port: 8001
eureka:
  client:
    service-url:
      defaultZone: http://peer2:8002/eureka/,http://peer3:8003/eureka/
  instance:
    hostname: peer1
spring:
  application:
    name: eurekaServer


