server:
  port: 8002
eureka:
  client:
    service-url:
      defaultZone: http://peer1:8001/eureka/,http://peer3:8003/eureka/
  instance:
    hostname: peer2
spring:
  application:
    name: eurekaServer